# -*- mode: python ; coding: utf-8 -*-

def filter_binaries(binaries):
    included_binaries = []
    for binary in binaries:
        if not binary[0].endswith((
            'Qt63DRender.dll',
            'Qt63DQuickScene2D.dll',
            'Qt63DQuickRender.dll',
            'Qt63DQuickInput.dll',
            'Qt63DQuickExtras.dll',
            'Qt63DQuickAnimation.dll',
            'Qt63DQuick.dll',
            'Qt63DLogic.dll',
            'Qt63DInput.dll',
            'Qt63DExtras.dll',
            'Qt63DCore.dll',
            'Qt63DAnimation.dll',
            'Qt6Charts.dll',
            'Qt6ChartsQml.dll',
            'Qt6Concurrent.dll',
            'Qt6DataVisualization.dll',
            'Qt6DataVisualizationQml.dll',
            'Qt6Graphs.dll',
            'Qt6LabsAnimation.dll',
            'Qt6LabsFolderListModel.dll',
            'Qt6LabsQmlModels.dll',
            'Qt6LabsSettings.dll',
            'Qt6LabsSharedImage.dll',
            'Qt6LabsWavefrontMesh.dll',
            'Qt6Location.dll',
            'Qt6Multimedia.dll',
            'Qt6MultimediaQuick.dll',
            'Qt6OpenGLWidgets.dll',
            'Qt6Pdf.dll',
            'Qt6PdfQuick.dll',
            'Qt6Positioning.dll',
            'Qt6PositioningQuick.dll',
            'Qt6QmlCore.dll',
            'Qt6QmlLocalStorage.dll',
            'Qt6QmlXmlListModel.dll',
            'Qt6Quick3D.dll',
            'Qt6Quick3DAssetImport.dll',
            'Qt6Quick3DAssetUtils.dll',
            'Qt6Quick3DEffects.dll',
            'Qt6Quick3DHelpers.dll',
            'Qt6Quick3DHelpersImpl.dll',
            'Qt6Quick3DParticleEffects.dll',
            'Qt6Quick3DParticles.dll',
            'Qt6Quick3DRuntimeRender.dll',
            'Qt6Quick3DSpatialAudio.dll',
            'Qt6Quick3DUtils.dll',
            'Qt6QuickControls2Imagine.dll',
            'Qt6QuickControls2ImagineStyleImpl.dll',
            'Qt6QuickControls2Material.dll',
            'Qt6QuickControls2MaterialStyleImpl.dll',
            'Qt6QuickControls2Universal.dll',
            'Qt6QuickControls2UniversalStyleImpl.dll',
            'Qt6QuickControls2WindowsStyleImpl.dll',
            'Qt6QuickDialogs2.dll',
            'Qt6QuickDialogs2QuickImpl.dll',
            'Qt6QuickDialogs2Utils.dll',
            'Qt6QuickParticles.dll',
            'Qt6QuickShapes.dll',
            'Qt6QuickTest.dll',
            'Qt6QuickTimeline.dll',
            'Qt6QuickTimelineBlendTrees.dll',
            'Qt6RemoteObjects.dll',
            'Qt6RemoteObjectsQml.dll',
            'Qt6Scxml.dll',
            'Qt6ScxmlQml.dll',
            'Qt6Sensors.dll',
            'Qt6SensorsQuick.dll',
            'Qt6ShaderTools.dll',
            'Qt6SpatialAudio.dll',
            'Qt6Sql.dll',
            'Qt6StateMachine.dll',
            'Qt6StateMachineQml.dll',
            'Qt6Test.dll',
            'Qt6TextToSpeech.dll',
            'Qt6VirtualKeyboard.dll',
            'Qt6VirtualKeyboardSettings.dll',
            'Qt6WebChannel.dll',
            'Qt6WebChannelQuick.dll',
            'Qt6WebEngineCore.dll',
            'Qt6WebEngineQuick.dll',
            'Qt6WebEngineQuickDelegatesQml.dll',
            'Qt6WebSockets.dll',
        )):
            included_binaries.append(binary)
    return included_binaries

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='OBS Recording Overlay',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='setup/logo.ico'
)
coll = COLLECT(
    exe,
    filter_binaries(a.binaries),
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='app',
)
