from typing import Protocol

from PySide6.QtCore import Slot


class ISettingsController(Protocol):
    def get_url(self) -> str: ...
    def set_url(self, value: str) -> None: ...

    def get_port(self) -> str: ...
    def set_port(self, value: str) -> None: ...

    def get_password(self) -> str: ...
    def set_password(self, value: str) -> None: ...

    @Slot(str, str, str)
    def save_settings(self, url: str, port: str, password: str) -> None: ...
